
export const servicios =["Mantenimiento Pestañas Pelo a Pelo",
"Postura Pestañas Premium",
"Postura Pestañas Basico",
"Postura Pestañas Vol Ruso",
"Retiro de Pestañas",
"Perfilación Cejas cuchilla",
"Perfilación Cejas con cera",
"Cejas Semipermanentes cuchilla",
"Cejas Semipermanentes cera",
"Cejas Semipermanentes",
"Mapa de Cejas",
"Lifting de Pestañas",
"Laminado de Cejas",
"Cepillo Desechables",
"Cepillo de Lujo",
"Espuma limpiadora",
"Sellante",
"Parche",
"Desmaquillante",
"Depilacion Labio Superior",
"Depilacion Axila",
"Depilacion Media Pierna",
"Depilacion Pierna Completa",
"Depilacion fosas nasales",
"Procedimientos SENA",
]


export const estilistas = ["Daniela",
"Jhoana",
"Eclis",
"Lineth",
"Margareth",
"Giomar",
"Producto",
]